---
driver:
  name: vagrant
  vm_hostname: chef.sweeper.io
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d ./vendor
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef_server]
    attributes:
